name: Trigger OpenShift Build

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot8006163434:AAFglGBFQZssn33_w4E1ZF08UTMVxkj58kA/sendMessage" \
            -d chat_id=742642835 \
            -d text="🚨 Merge to Main/Master Branch 🚨\nA merge has been made to the main/master branch. Diganti oleh Nerissa"